### ISSUE TITLE
Defer integration with Dynamic Code Brand Checks?

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#397]
I think it makes sense if we defer integration with the [Dynamic Code Brand Checks](https://tc39.es/proposal-dynamic-code-brand-checks/) Ecmascript proposal as it's only Stage 1 so is far from implementation ready?

Would be good if this could be removed from the current spec draft and maybe moved to a PR instead so we don't lose it but it's not in the Level 1 version?

cc @bkardell @mbrodesser-Igalia

**Comment by koto** [comment]
This might be problematic, since enforcement for all sinks is controlled by a single CSP `require-trusted-types 'script'`. 

Chromium implemented the enforcements (I think there are some implementation issues with Function constructor only - https://bugs.chromium.org/p/chromium/issues/detail?id=1087743). If there is a difference in semantics for this keyword across implementations, this causes either a bypass on one implementation or unexpected JS exceptions on another.

The way out would be to implement more granular keywords, with the implementations without the ECMAScript integrations recognizing only `script-eval` and `script-dom`, and ignore `script`; though I don't see an easy way to explain why multiple keywords are needed to the authors (in the end, not guarding eval means XSS).

**Comment by lukewarlow** [comment]
It seems problematic to rely on a stage 1 ecmascript proposal, are there major blockers to progressing that through tc39?

**Comment by lukewarlow** [comment]
Related https://github.com/w3c/trusted-types/issues/207
