### ISSUE TITLE
There's a lack of test coverage over the namespace aspect of getPropertyType

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#429]
A WPT test (or subtest) should be added to test the elementNs parameter of getPropertyType

**Comment by fred-wang** [comment]
Uploaded something there: https://phabricator.services.mozilla.com/D226122

**Comment by fred-wang** [comment]
I think this can be closed since that's addressed by https://github.com/web-platform-tests/wpt/commit/3f6b218762b8df9b6d14e19d3f115b0722c3289f  and https://github.com/web-platform-tests/wpt/commit/da5e743e23b8ab8f72a228d45b074d75edf5cd3f#diff-bbed4f84dea0d96f255fd583d63ad05036783ba823398da9fa38d6496f31432eR118

https://github.com/web-platform-tests/wpt/pull/48769 will also check explicit null values.
