### ISSUE TITLE
Is parseFromString where the type is "application/xml" an actual risk?

### ISSUE THREAD

**Issue by technion** [w3c/trusted-types#467]
I'm dealing with a third party API that returns XML data and I'm struggling with how to use Trusted Types while parsing this. The current implementation appears to direct through some non obvious paths.

I've been through issues like this:

https://github.com/GoogleChrome/web.dev/issues/6890

Where it's explained that parsing HTML is basically tricky and forces you to create a policy that just "allows all" and then work carefully. But as far as I can see there's no risk in doing the below, as parsing XML doesn't execute script tags and there's nowhere to inject XSS as far as I can see, so this should be safe:
```
const r = d.parseFromString(data, "application/xml");
// error check here
const nodelist= r.querySelectorAll("Nodes");
// do stuff with each node.textContent
```

I have naively expected you could put the above in a TrustedType policy itself, hardcoding those values, as your way of ensuring the input is trusted. Unfortunately it seems seems sinks can't even be used within a policy. 

The only way I can find to make this work is effectively first running through a policy of `createHTML: (string: string) => { return string; }` , which feels very wrong for the purposes of Trusted Types, creating an "allow all" policy.

It feels like there should be additional pathway here as parsing XML is fairly common, and it feels like the spec should allow for a way to do this without the above "allow all" policy.

Edit: Just adding that such a piece of code appears to violate the spec in that the output from the createHTML policy clearly isn't safe for use in a sink, and it's only made "safe" due to the way it's used outside of the policy.

**Comment by Sora2455** [comment]
My understanding is that you create an "allow all" policy that is only used in your sanitiser code:
1) Inside a closure so that no other code can get a reference to it
2) With a name in the CSP policy so that nobody else can create a policy with this name

If you do both of those things, than despite the existence of a policy that blindly wraps any input as trusted, that policy isn't a problem because the only place that policy can be used is to feed the 'trusted' HTML string into a sanitiser.

Once the native sanitizer API is supported, you can use that without needing an 'allow-all' policy.

**Comment by annevk** [comment]
I don't see how XML is relevant here. `XMLParser()` has the exact same properties whether you feed it HTML or XML. Same for `XMLHttpRequest`.
