### ISSUE TITLE
Create a Trusted Type Policy seems to directly set properties to callbacks

### ISSUE THREAD

**Issue by annevk** [w3c/trusted-types#470]
> Set policyOptions [createHTML](https://w3c.github.io/trusted-types/dist/spec/#dom-trustedtypepolicy-createhtml) property to option’s [createHTML](https://w3c.github.io/trusted-types/dist/spec/#dom-trustedtypepolicyoptions-createhtml) property value.

What does this actually mean? And how does this work given that these properties are declared as methods in IDL?

**Comment by lukewarlow** [comment]
It's basically copying the options argument through to be stored on the TrustedTypePolicy itself for you to later call when creating trusted types from the policy.

As for why the spec is copying the properties individually rather than just putting the options object into the internal slot I'm not entirely sure.

Also they're declared as callbacks rather than methods (which I don't think are strictly speaking the same thing in IDL). So I think that should work?

**Comment by annevk** [comment]
Oh I think I understand now. There's an internal dictionary that holds the callbacks. So the main problem is the lack of Infra map notation. That's probably best tracked separately. Thanks.
