### ISSUE TITLE
WPT for CSP header `trusted-types 'none' 'none'` missing

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#508]
Behavior should equal the one for `trusted-types 'none'`.

**Comment by ziransun** [comment]
Is it valid to set the `trusted-types  'none' 'none' ` since 'none' has no effect unless it is the only expression in the directive value?

**Comment by lukewarlow** [comment]
Have you tested Chromiums or safari tech preview's behaviour here? 

The spec is ambiguous imo. It says the value only contains a keyword 'none'. Well two duplicate keywords aren't 'a keyword'. I think it depends on if there's any handling for discarding duplicates inside of CSP parsing?

![Screenshot_20240502-134711.png](https://github.com/w3c/trusted-types/assets/32498324/b3937d42-71f7-4666-a616-756936208f49)

**Comment by ziransun** [comment]
Yes, I have tried with Chromiums and safari. Apart from having the same result as one "none", it has complains like - 
`The value of the Content Security Policy directive 'trusted_types' contains an invalid policy: 'none'. It will be ignored. Note that 'none' has no effect unless it is the only expression in the directive value.`

**Comment by mbrodesser-Igalia** [comment]
> I think it should behave the same as just 1 existing but the spec should be clarified too in that case.

Agreed.

**Comment by lukewarlow** [comment]
So after some more thinking I want to clarify the above comment.

`trusted-types 'none';` and `trusted-types 'none' 'none';` should and DO behave the same both in the spec and in implementation, no policies are allowed. This is because they're both equivalent to `trusted-types;`

`trusted-types 'none' foobar;` and `trusted-types 'none' 'none' foobar;` also both behave the same (policy name foobar is allowed).

I actually don't think the spec is ambiguous here.

**Comment by lukewarlow** [comment]
There are now tests for this

**Comment by mbrodesser-Igalia** [comment]
(It's helpful to link the PR for the test to the issue, in case it gets reverted or so.)

**Comment by ziransun** [comment]
https://github.com/WebKit/WebKit/pull/28044
