### ISSUE TITLE
"Should Trusted Type policy creation be blocked by Content Security Policy?" passes "directive" instead of directive's name to "Create a violation object for global, policy, and directive" 

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#509]
https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-should-trusted-type-policy-creation-be-blocked-by-content-security-policy,
step 2.8,

Fix: pass directive's name.

**Comment by koto** [comment]
Not sure what you mean, I see [a string being passed there](https://github.com/w3c/trusted-types/blob/e8ff92bf7786916178f3a170d83a13d2a3e36196/spec/index.bs#L1474), and the blame shows that this was like that since at least https://github.com/w3c/trusted-types/commit/3fbb1ea7542c0b905c40d2d4ddd55aa7c9aca41a.
